### ISSUE TITLE
Question: What extra steps should i follow if my OCP4 cluster is using a proxy ?

### ISSUE THREAD

**Issue by calebjse** [vaibhavjain4/jenkins-demo-app#1]
Hello, i'm trying to repeat your test deploy creating the pipeline and applying to OCP4, but i got this error:
Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/OpenShift Test Pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Create New Project)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy App)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] echo
Hello from project caleb-test3 in cluster https://api.ocpprod.gp.inet:6443
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: new-app returned an error;
{err=error: unable to load template file "https://github.com/redhat-developer/s2i-dotnetcore-ex": Get https://github.com/redhat-developer/s2i-dotnetcore-ex: dial tcp 140.82.113.3:443: i/o timeout
error: git ls-remote failed with: execution of git ls-remote https://github.com/redhat-developer/s2i-dotnetcore-ex timed out after 30s;  local file access failed with: stat https://github.com/redhat-developer/s2i-dotnetcore-ex: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "https://github.com/redhat-developer/s2i-dotnetcore-ex"

Argument 'https://github.com/redhat-developer/s2i-dotnetcore-ex' was classified as an image, image~source, or loaded template reference.

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
, verb=new-app, cmd=oc --server=https://api.ocpprod.gp.inet:6443 --insecure-skip-tls-verify --namespace=caleb-test3 --token=XXXXX new-app https://github.com/redhat-developer/s2i-dotnetcore-ex -o=json , out=, status=1}

Finished: FAILURE

I guess the failure is for the proxy that my cluster is using, because if i try to repeat the command shown in the error above, the app deploy with no issue. (since bastion)
[root@lnxsrpvli0136 ~]# oc --server=https://api.ocpprod.gp.inet:6443 --insecure-skip-tls-verify --namespace=caleb-test3 --token=XXXX new-app https://github.com/openshift/ruby-hello-world
warning: Cannot check if git requires authentication.
--> Found container image 712cc38 (11 days old) from Docker Hub for "centos/ruby-25-centos7"

    Ruby 2.5
    --------
    Ruby 2.5 available as container is a base platform for building and running various Ruby 2.5 applications and frameworks. Ruby is the interpreted scripting language for quick and easy object-oriented programming. It has many features to process text files and to do system management tasks (as in Perl). It is simple, straight-forward, and extensible.

    Tags: builder, ruby, ruby25, rh-ruby25

    * An image stream tag will be created as "ruby-25-centos7:latest" that will track the source image
    * A Docker build using source code from https://github.com/openshift/ruby-hello-world will be created
      * The resulting image will be pushed to image stream tag "ruby-hello-world:latest"
      * Every time "ruby-25-centos7:latest" changes a new build will be triggered
      * WARNING: this source repository may require credentials.
                 Create a secret with your git credentials and use 'oc set build-secret' to assign it to the build config.

--> Creating resources ...
    imagestream.image.openshift.io "ruby-25-centos7" created
    imagestream.image.openshift.io "ruby-hello-world" created
    buildconfig.build.openshift.io "ruby-hello-world" created
    deployment.apps "ruby-hello-world" created
    service "ruby-hello-world" created
--> Success
    Build scheduled, use 'oc logs -f bc/ruby-hello-world' to track its progress.
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/ruby-hello-world'
    Run 'oc status' to view your app.

I guess the outtime error is for the proxy of my cluster, i guess is trying to download the template image from internet but isn't setted up or something like this.
Thanks in advance

**Comment by calebjse** [comment]
Sorry, the first log uploaded was when i try to deploy another image.
Log below corresponds to your test deploy using ruby 
Started by user admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/OpenShift Test Pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Create New Project)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy App)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] echo
Hello from project jenkins-testc1 in cluster https://api.ocpprod.gp.inet:6443
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: new-app returned an error;
{err=error: unable to load template file "https://github.com/openshift/ruby-hello-world": Get https://github.com/openshift/ruby-hello-world: dial tcp 140.82.114.3:443: i/o timeout
error: git ls-remote failed with: execution of git ls-remote https://github.com/openshift/ruby-hello-world timed out after 30s;  local file access failed with: stat https://github.com/openshift/ruby-hello-world: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "https://github.com/openshift/ruby-hello-world"

Argument 'https://github.com/openshift/ruby-hello-world' was classified as an image, image~source, or loaded template reference.

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
, verb=new-app, cmd=oc --server=https://api.ocpprod.gp.inet:6443 --insecure-skip-tls-verify --namespace=jenkins-testc1 --token=XXXXX new-app https://github.com/openshift/ruby-hello-world -o=json , out=, status=1}

Finished: FAILURE

**Comment by calebjse** [comment]
Sorry,was a mistake this wasn't the correct github project.

**Comment by vaibhavjain4** [comment]
In my opinion no changes in pipeline are required as network level connectivity is provided through underlying and openshift platform. You may test with some other link that seems to be working for you or can try hosting a git repo in your local reachable environment itself.
